### ISSUE TITLE
A shinyapp using `pinyin` package

### ISSUE THREAD

**Issue by boltomli** [pzhaonet/pinyin#10]
A basic app that I'd use for other purpose in future, but you might be interested since you have a to-do for shinyapp <https://github.com/boltomli/MyShinyApps/tree/master/hanying>

**Comment by pzhaonet** [comment]
Thank you for the info. It is fantastic to develop such a nice shinyapp, although it is not what I mean in the to-do list. 

However, your app does not function properly on my computer. The error is:

```
Listening on http://127.0.0.1:3218
Warning: Error in switch: EXPR must be a length 1 vector
  142: <reactive:dict_tone> [D:\temp\-test\MyShinyApps-master\hanying/app.R#46]
  126: dict_tone
  119: <reactive:dict_data> [D:\temp\-test\MyShinyApps-master\hanying/app.R#55]
  103: dict_data
   96: renderText [D:\temp\-test\MyShinyApps-master\hanying/app.R#107]
   95: func
   82: origRenderFunc
   81: output$convert_result
    1: runApp
```

Unfortunately, I have no time for debugging, but it would be appreciated if you could debug it and make a PR to pinyin package.

Good luck!

**Comment by boltomli** [comment]
Sure, I'll try with a different design so it could better suit the package.

I wrote the shiny app quicker than I expected so introduced more dependencies beyond.
