### ISSUE TITLE
rework on this package

### ISSUE THREAD

**Issue by tcgriffith** [pzhaonet/pinyin#11]
I think I've learned enough to make another PR to improve this package. I'll draft a new PR when I got time.

Things I aim to achieve in the PR:

- A new function to convert 汉语 to pinyin with speed in mind.

- lazyload default dictionary data in the package. Users can directly call the function after install, without having to manually load the dictionary.

**Comment by tcgriffith** [comment]
At the same time, I won't touch existing things.

**Comment by pzhaonet** [comment]
Great. Looking forward to the PR.
