### ISSUE TITLE
how to get the first letter of the pinyin

### ISSUE THREAD

**Issue by perlatex** [pzhaonet/pinyin#17]
hello zhao,
     can pinyin get the first letter of the pinyin according to the string of Chinese characters ?
for example, 
Qingdao --> qd
wang, xiaoer  --> w, xe

thanks.

**Comment by pzhaonet** [comment]
It can only translate Chinese into pinyin, like:

```
> library(pinyin)
> mylib <- pydic(only_first_letter = TRUE, dic = "pinyin2")
> py("青岛", dic = mylib, sep = "")
青岛 
"qd"
```
