### ISSUE TITLE
Better dictionary

### ISSUE THREAD

**Issue by psychelzh** [pzhaonet/pinyin#18]
The pinyin for "更" (geng4/geng1) is correct in "pinyin" but not in "pinyin2":

``` r
library(pinyin)
suppressWarnings(py("更", dic = pydic(method = "tone", multi = TRUE, dic = "pinyin")))
#>            更 
#> "geng4/geng1"
py("更", dic = pydic(method = "tone", multi = TRUE, dic = "pinyin2"))
#>      更 
#> "geng4"
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The pinyin for "迹" (ji4) is correct in "pinyin2" but not in "pinyin":

``` r
library(pinyin)
suppressWarnings(py("迹", dic = pydic(method = "tone", multi = TRUE, dic = "pinyin")))
#>    迹 
#> "ji1"
py("迹", dic = pydic(method = "tone", multi = TRUE, dic = "pinyin2"))
#>    迹 
#> "ji4"
```

<sup>Created on 2021-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In this way, seemingly either of these two dictionaries is error-proof.

**Comment by pzhaonet** [comment]
At the moment no dictionary is perfect. You could define your own dictionary and load it. Technically it is simply a find-and-replace work.
