### ISSUE TITLE
unexpected number when converting "大同市"

### ISSUE THREAD

**Issue by caimiao0714** [pzhaonet/pinyin#8]
Hi Peng,

When I try to convert the Chinese characters "大同", the number 5 kick in unexpectedly. Is this a bug or made intentionally?

```r
> devtools::install_github('pzhaonet/pinyin')
> require('pinyin')
> mypy = pydic(method = 'toneless', dic = 'pinyin2')
> py("大同市",  dic = mypy, sep = '')
     大同 
"datong5"
```

Thank you!

**Comment by pzhaonet** [comment]
It was a bug. Now it has been fixed. Please update it to the lastest version.

Thank you for your feedback!

**Comment by caimiao0714** [comment]
Got it. Thank you Peng!
I am curious about how the code produces this 5 in the English letters.
Could you explain a little bit about it if it is not too complex?
Thank you!

**Comment by pzhaonet** [comment]
The previous version removed the tones 1 -- 4 when you chose `method = 'toneless'`. However, the dictionary 'pinyin2' gives 'tong5'. I don't know what it means, but the new version of 'pinyin' removes all digits.

**Comment by caimiao0714** [comment]
Got it. Thank you!
